#include "test_common.h"
#include "common_validation.h"
static void test_required_text(void){CU_ASSERT_FALSE(ValidateName(""));CU_ASSERT_TRUE(ValidateName("Arun Kumar"));CU_ASSERT_FALSE(ValidateName("Arun123"));CU_ASSERT_TRUE(ValidateAddress("12 North Street"));CU_ASSERT_FALSE(ValidateAddress(""));}
static void test_email(void){CU_ASSERT_TRUE(ValidateEmail("donor@test.com"));CU_ASSERT_FALSE(ValidateEmail("donortest.com"));CU_ASSERT_FALSE(ValidateEmail("donor@test"));CU_ASSERT_FALSE(ValidateEmail("@test.com"));}
static void test_phone(void){CU_ASSERT_TRUE(ValidatePhoneNumber("9876543210"));CU_ASSERT_FALSE(ValidatePhoneNumber("987654321"));CU_ASSERT_FALSE(ValidatePhoneNumber("98765432101"));CU_ASSERT_FALSE(ValidatePhoneNumber("98765A3210"));CU_ASSERT_FALSE(ValidatePhoneNumber("98765-3210"));}
static void test_password(void){CU_ASSERT_TRUE(ValidatePassword("Strong@123"));CU_ASSERT_FALSE(ValidatePassword("Pass1!"));CU_ASSERT_FALSE(ValidatePassword("password123"));CU_ASSERT_FALSE(ValidatePassword("PASSWORD@1"));}
static void test_blood_group(void){BmsBloodGroup_t bg=BMS_BLOOD_GROUP_INVALID;CU_ASSERT_TRUE(ValidateBloodGroup("A+"));CU_ASSERT_TRUE(ValidateBloodGroup("A Rh Positive"));CU_ASSERT_TRUE(ValidateBloodGroup("O Negative"));CU_ASSERT_FALSE(ValidateBloodGroup("X+"));ASSERT_OK(ParseBloodGroup("AB-",&bg));CU_ASSERT_EQUAL(bg,BMS_BLOOD_GROUP_AB_NEGATIVE);}
static void test_numeric_and_date(void){CU_ASSERT_TRUE(ValidateAge(18U));CU_ASSERT_TRUE(ValidateAge(65U));CU_ASSERT_FALSE(ValidateAge(17U));CU_ASSERT_FALSE(ValidateAge(66U));CU_ASSERT_TRUE(ValidateWeight(45U));CU_ASSERT_FALSE(ValidateWeight(44U));CU_ASSERT_TRUE(ValidateUnits(1U));CU_ASSERT_FALSE(ValidateUnits(0U));CU_ASSERT_TRUE(ValidateDate("2024-02-29"));CU_ASSERT_FALSE(ValidateDate("2023-02-29"));CU_ASSERT_FALSE(ValidateDate("31-13-2025"));}
static void test_ids_roles(void){CU_ASSERT_TRUE(ValidateUserId(1U));CU_ASSERT_FALSE(ValidateUserId(0U));CU_ASSERT_TRUE(ValidateDonorId(1U));CU_ASSERT_TRUE(ValidateHospitalId(1U));CU_ASSERT_TRUE(ValidateRequestId(1U));CU_ASSERT_TRUE(ValidateUserRoleValue(BMS_ROLE_ADMIN));CU_ASSERT_FALSE(ValidateUserRoleValue(BMS_ROLE_INVALID));}
void RegisterValidationTests(void){CU_pSuite s=CU_add_suite("Validation",NULL,NULL);CU_add_test(s,"required text",test_required_text);CU_add_test(s,"email formats",test_email);CU_add_test(s,"phone formats",test_phone);CU_add_test(s,"password policy",test_password);CU_add_test(s,"blood group aliases",test_blood_group);CU_add_test(s,"age weight units dates",test_numeric_and_date);CU_add_test(s,"IDs and roles",test_ids_roles);}
